// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.openstack.networking.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetRouterExternalFixedIp {
    /**
     * @return The IP address to set on the router.
     * 
     */
    private final @Nullable String ipAddress;
    private final @Nullable String subnetId;

    @CustomType.Constructor
    private GetRouterExternalFixedIp(
        @CustomType.Parameter("ipAddress") @Nullable String ipAddress,
        @CustomType.Parameter("subnetId") @Nullable String subnetId) {
        this.ipAddress = ipAddress;
        this.subnetId = subnetId;
    }

    /**
     * @return The IP address to set on the router.
     * 
     */
    public Optional<String> ipAddress() {
        return Optional.ofNullable(this.ipAddress);
    }
    public Optional<String> subnetId() {
        return Optional.ofNullable(this.subnetId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRouterExternalFixedIp defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String ipAddress;
        private @Nullable String subnetId;

        public Builder() {
    	      // Empty
        }

        public Builder(GetRouterExternalFixedIp defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ipAddress = defaults.ipAddress;
    	      this.subnetId = defaults.subnetId;
        }

        public Builder ipAddress(@Nullable String ipAddress) {
            this.ipAddress = ipAddress;
            return this;
        }
        public Builder subnetId(@Nullable String subnetId) {
            this.subnetId = subnetId;
            return this;
        }        public GetRouterExternalFixedIp build() {
            return new GetRouterExternalFixedIp(ipAddress, subnetId);
        }
    }
}
