// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.OpenStack.BlockStorage
{
    public static class GetAvailabilityZonesV3
    {
        /// <summary>
        /// Use this data source to get a list of Block Storage availability zones from OpenStack
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using OpenStack = Pulumi.OpenStack;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var zones = OpenStack.BlockStorage.GetAvailabilityZonesV3.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetAvailabilityZonesV3Result> InvokeAsync(GetAvailabilityZonesV3Args? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAvailabilityZonesV3Result>("openstack:blockstorage/getAvailabilityZonesV3:getAvailabilityZonesV3", args ?? new GetAvailabilityZonesV3Args(), options.WithDefaults());

        /// <summary>
        /// Use this data source to get a list of Block Storage availability zones from OpenStack
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using OpenStack = Pulumi.OpenStack;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var zones = OpenStack.BlockStorage.GetAvailabilityZonesV3.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetAvailabilityZonesV3Result> Invoke(GetAvailabilityZonesV3InvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAvailabilityZonesV3Result>("openstack:blockstorage/getAvailabilityZonesV3:getAvailabilityZonesV3", args ?? new GetAvailabilityZonesV3InvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to get a list of Block Storage availability zones from OpenStack
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using OpenStack = Pulumi.OpenStack;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var zones = OpenStack.BlockStorage.GetAvailabilityZonesV3.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetAvailabilityZonesV3Result> Invoke(GetAvailabilityZonesV3InvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAvailabilityZonesV3Result>("openstack:blockstorage/getAvailabilityZonesV3:getAvailabilityZonesV3", args ?? new GetAvailabilityZonesV3InvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAvailabilityZonesV3Args : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The region in which to obtain the Block Storage client.
        /// If omitted, the `Region` argument of the provider is used.
        /// </summary>
        [Input("region")]
        public string? Region { get; set; }

        /// <summary>
        /// The `State` of the availability zones to match. Can
        /// either be `Available` or `Unavailable`. Default is `Available`.
        /// </summary>
        [Input("state")]
        public string? State { get; set; }

        public GetAvailabilityZonesV3Args()
        {
        }
        public static new GetAvailabilityZonesV3Args Empty => new GetAvailabilityZonesV3Args();
    }

    public sealed class GetAvailabilityZonesV3InvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The region in which to obtain the Block Storage client.
        /// If omitted, the `Region` argument of the provider is used.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// The `State` of the availability zones to match. Can
        /// either be `Available` or `Unavailable`. Default is `Available`.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        public GetAvailabilityZonesV3InvokeArgs()
        {
        }
        public static new GetAvailabilityZonesV3InvokeArgs Empty => new GetAvailabilityZonesV3InvokeArgs();
    }


    [OutputType]
    public sealed class GetAvailabilityZonesV3Result
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The names of the availability zones, ordered alphanumerically, that
        /// match the queried `State`.
        /// </summary>
        public readonly ImmutableArray<string> Names;
        /// <summary>
        /// See Argument Reference above.
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// See Argument Reference above.
        /// </summary>
        public readonly string? State;

        [OutputConstructor]
        private GetAvailabilityZonesV3Result(
            string id,

            ImmutableArray<string> names,

            string region,

            string? state)
        {
            Id = id;
            Names = names;
            Region = region;
            State = state;
        }
    }
}
