provider: openstack
major-version: 5
esc:
    enabled: true
env:
    OS_AUTH_URL: "https://auth.cloud.ovh.net/v3/"
    OS_IDENTITY_API_VERSION: 3
    OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
    OS_REGION_NAME: UK1
    OS_TENANT_ID: "9d596a0506974e0f8c79673edf0bbdd3"
    OS_TENANT_NAME: "9616699805113213"
    OS_USERNAME: "jrGMbHHjkUQ7"
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
