// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.OpenStack.Database.Inputs
{

    public sealed class InstanceDatastoreGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Database engine type to be used in new instance. Changing this
        /// creates a new instance.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// Version of database engine type to be used in new instance.
        /// Changing this creates a new instance.
        /// </summary>
        [Input("version", required: true)]
        public Input<string> Version { get; set; } = null!;

        public InstanceDatastoreGetArgs()
        {
        }
        public static new InstanceDatastoreGetArgs Empty => new InstanceDatastoreGetArgs();
    }
}
