// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.openstack.identity.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class UserMultiFactorAuthRule {
    /**
     * @return A list of authentication plugins that the user must
     * authenticate with.
     * 
     */
    private List<String> rules;

    private UserMultiFactorAuthRule() {}
    /**
     * @return A list of authentication plugins that the user must
     * authenticate with.
     * 
     */
    public List<String> rules() {
        return this.rules;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(UserMultiFactorAuthRule defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> rules;
        public Builder() {}
        public Builder(UserMultiFactorAuthRule defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.rules = defaults.rules;
        }

        @CustomType.Setter
        public Builder rules(List<String> rules) {
            if (rules == null) {
              throw new MissingRequiredPropertyException("UserMultiFactorAuthRule", "rules");
            }
            this.rules = rules;
            return this;
        }
        public Builder rules(String... rules) {
            return rules(List.of(rules));
        }
        public UserMultiFactorAuthRule build() {
            final var _resultValue = new UserMultiFactorAuthRule();
            _resultValue.rules = rules;
            return _resultValue;
        }
    }
}
