// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.OpenStack.Networking.Inputs
{

    public sealed class PortFixedIpArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// IP address desired in the subnet for this port. If
        /// you don't specify `IpAddress`, an available IP address from the specified
        /// subnet will be allocated to this port. This field will not be populated if it
        /// is left blank or omitted. To retrieve the assigned IP address, use the
        /// `AllFixedIps` attribute.
        /// </summary>
        [Input("ipAddress")]
        public Input<string>? IpAddress { get; set; }

        /// <summary>
        /// Subnet in which to allocate IP address for
        /// this port.
        /// </summary>
        [Input("subnetId")]
        public Input<string>? SubnetId { get; set; }

        public PortFixedIpArgs()
        {
        }
        public static new PortFixedIpArgs Empty => new PortFixedIpArgs();
    }
}
