# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from .. import utilities, tables

class Vip(pulumi.CustomResource):
    """
    Manages a V1 load balancer vip resource within OpenStack.
    """
    def __init__(__self__, __name__, __opts__=None, address=None, admin_state_up=None, conn_limit=None, description=None, floating_ip=None, name=None, persistence=None, pool_id=None, port=None, protocol=None, region=None, subnet_id=None, tenant_id=None):
        """Create a Vip resource with the given unique name, props, and options."""
        if not __name__:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(__name__, str):
            raise TypeError('Expected resource name to be a string')
        if __opts__ and not isinstance(__opts__, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        __props__['address'] = address

        __props__['admin_state_up'] = admin_state_up

        __props__['conn_limit'] = conn_limit

        __props__['description'] = description

        __props__['floating_ip'] = floating_ip

        __props__['name'] = name

        __props__['persistence'] = persistence

        if not pool_id:
            raise TypeError('Missing required property pool_id')
        __props__['pool_id'] = pool_id

        if not port:
            raise TypeError('Missing required property port')
        __props__['port'] = port

        if not protocol:
            raise TypeError('Missing required property protocol')
        __props__['protocol'] = protocol

        __props__['region'] = region

        if not subnet_id:
            raise TypeError('Missing required property subnet_id')
        __props__['subnet_id'] = subnet_id

        __props__['tenant_id'] = tenant_id

        __props__['port_id'] = None

        super(Vip, __self__).__init__(
            'openstack:loadbalancer/vip:Vip',
            __name__,
            __props__,
            __opts__)


    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

