// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.openstack.firewall.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetPolicyResult {
    /**
     * @return The audit status of the firewall policy.
     * 
     */
    private Boolean audited;
    /**
     * @return The description of the firewall policy.
     * 
     */
    private String description;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return See Argument Reference above.
     * 
     */
    private @Nullable String name;
    /**
     * @return See Argument Reference above.
     * 
     */
    private @Nullable String policyId;
    /**
     * @return See Argument Reference above.
     * 
     */
    private String region;
    /**
     * @return The array of one or more firewall rules that comprise the policy.
     * 
     */
    private List<String> rules;
    /**
     * @return The sharing status of the firewall policy.
     * 
     */
    private Boolean shared;
    /**
     * @return See Argument Reference above.
     * 
     */
    private String tenantId;

    private GetPolicyResult() {}
    /**
     * @return The audit status of the firewall policy.
     * 
     */
    public Boolean audited() {
        return this.audited;
    }
    /**
     * @return The description of the firewall policy.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return See Argument Reference above.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return See Argument Reference above.
     * 
     */
    public Optional<String> policyId() {
        return Optional.ofNullable(this.policyId);
    }
    /**
     * @return See Argument Reference above.
     * 
     */
    public String region() {
        return this.region;
    }
    /**
     * @return The array of one or more firewall rules that comprise the policy.
     * 
     */
    public List<String> rules() {
        return this.rules;
    }
    /**
     * @return The sharing status of the firewall policy.
     * 
     */
    public Boolean shared() {
        return this.shared;
    }
    /**
     * @return See Argument Reference above.
     * 
     */
    public String tenantId() {
        return this.tenantId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPolicyResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean audited;
        private String description;
        private String id;
        private @Nullable String name;
        private @Nullable String policyId;
        private String region;
        private List<String> rules;
        private Boolean shared;
        private String tenantId;
        public Builder() {}
        public Builder(GetPolicyResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.audited = defaults.audited;
    	      this.description = defaults.description;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.policyId = defaults.policyId;
    	      this.region = defaults.region;
    	      this.rules = defaults.rules;
    	      this.shared = defaults.shared;
    	      this.tenantId = defaults.tenantId;
        }

        @CustomType.Setter
        public Builder audited(Boolean audited) {
            if (audited == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "audited");
            }
            this.audited = audited;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder policyId(@Nullable String policyId) {

            this.policyId = policyId;
            return this;
        }
        @CustomType.Setter
        public Builder region(String region) {
            if (region == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "region");
            }
            this.region = region;
            return this;
        }
        @CustomType.Setter
        public Builder rules(List<String> rules) {
            if (rules == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "rules");
            }
            this.rules = rules;
            return this;
        }
        public Builder rules(String... rules) {
            return rules(List.of(rules));
        }
        @CustomType.Setter
        public Builder shared(Boolean shared) {
            if (shared == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "shared");
            }
            this.shared = shared;
            return this;
        }
        @CustomType.Setter
        public Builder tenantId(String tenantId) {
            if (tenantId == null) {
              throw new MissingRequiredPropertyException("GetPolicyResult", "tenantId");
            }
            this.tenantId = tenantId;
            return this;
        }
        public GetPolicyResult build() {
            final var _resultValue = new GetPolicyResult();
            _resultValue.audited = audited;
            _resultValue.description = description;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.policyId = policyId;
            _resultValue.region = region;
            _resultValue.rules = rules;
            _resultValue.shared = shared;
            _resultValue.tenantId = tenantId;
            return _resultValue;
        }
    }
}
