// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages a V2 load balancer flavorprofile resource within OpenStack.
 *
 * > **Note:** This usually requires admin privileges.
 *
 * ## Example Usage
 *
 * ### Using jsonencode
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as openstack from "@pulumi/openstack";
 *
 * const flavorprofile1 = new openstack.loadbalancer.FlavorprofileV2("flavorprofile_1", {
 *     name: "amphora-single-profile",
 *     providerName: "amphora",
 *     flavorData: JSON.stringify({
 *         loadbalancer_topology: "SINGLE",
 *     }),
 * });
 * ```
 *
 * ### Using plain string
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as openstack from "@pulumi/openstack";
 *
 * const flavorprofile1 = new openstack.loadbalancer.FlavorprofileV2("flavorprofile_1", {
 *     name: "amphora-single-profile",
 *     providerName: "amphora",
 *     flavorData: "{\"loadbalancer_topology\": \"SINGLE\"}",
 * });
 * ```
 *
 * ## Import
 *
 * flavorprofiles can be imported using their `id`. Example:
 *
 * ```sh
 * $ pulumi import openstack:loadbalancer/flavorprofileV2:FlavorprofileV2 flavorprofile_1 2a0f2240-c5e6-41de-896d-e80d97428d6b
 * ```
 */
export class FlavorprofileV2 extends pulumi.CustomResource {
    /**
     * Get an existing FlavorprofileV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FlavorprofileV2State, opts?: pulumi.CustomResourceOptions): FlavorprofileV2 {
        return new FlavorprofileV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'openstack:loadbalancer/flavorprofileV2:FlavorprofileV2';

    /**
     * Returns true if the given object is an instance of FlavorprofileV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FlavorprofileV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FlavorprofileV2.__pulumiType;
    }

    /**
     * String that passes the flavorData for the flavorprofile.
     * The data that are allowed depend on the `providerName` that is passed. jsonencode
     * can be used for readability as shown in the example above.
     * Changing this updates the existing flavorprofile.
     */
    declare public readonly flavorData: pulumi.Output<string>;
    /**
     * Name of the flavorprofile. Changing this updates the existing
     * flavorprofile.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The providerName that the flavorProfile will use.
     * Changing this updates the existing flavorprofile.
     */
    declare public readonly providerName: pulumi.Output<string>;
    /**
     * The region in which to obtain the V2 Networking client.
     * A Networking client is needed to create an LB member. If omitted, the
     * `region` argument of the provider is used. Changing this creates a new
     * LB flavorprofile.
     */
    declare public readonly region: pulumi.Output<string>;

    /**
     * Create a FlavorprofileV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FlavorprofileV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FlavorprofileV2Args | FlavorprofileV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FlavorprofileV2State | undefined;
            resourceInputs["flavorData"] = state?.flavorData;
            resourceInputs["name"] = state?.name;
            resourceInputs["providerName"] = state?.providerName;
            resourceInputs["region"] = state?.region;
        } else {
            const args = argsOrState as FlavorprofileV2Args | undefined;
            if (args?.flavorData === undefined && !opts.urn) {
                throw new Error("Missing required property 'flavorData'");
            }
            if (args?.providerName === undefined && !opts.urn) {
                throw new Error("Missing required property 'providerName'");
            }
            resourceInputs["flavorData"] = args?.flavorData;
            resourceInputs["name"] = args?.name;
            resourceInputs["providerName"] = args?.providerName;
            resourceInputs["region"] = args?.region;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const aliasOpts = { aliases: [{ type: "openstack:index/lbFlavorprofileV2:LbFlavorprofileV2" }] };
        opts = pulumi.mergeOptions(opts, aliasOpts);
        super(FlavorprofileV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FlavorprofileV2 resources.
 */
export interface FlavorprofileV2State {
    /**
     * String that passes the flavorData for the flavorprofile.
     * The data that are allowed depend on the `providerName` that is passed. jsonencode
     * can be used for readability as shown in the example above.
     * Changing this updates the existing flavorprofile.
     */
    flavorData?: pulumi.Input<string>;
    /**
     * Name of the flavorprofile. Changing this updates the existing
     * flavorprofile.
     */
    name?: pulumi.Input<string>;
    /**
     * The providerName that the flavorProfile will use.
     * Changing this updates the existing flavorprofile.
     */
    providerName?: pulumi.Input<string>;
    /**
     * The region in which to obtain the V2 Networking client.
     * A Networking client is needed to create an LB member. If omitted, the
     * `region` argument of the provider is used. Changing this creates a new
     * LB flavorprofile.
     */
    region?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a FlavorprofileV2 resource.
 */
export interface FlavorprofileV2Args {
    /**
     * String that passes the flavorData for the flavorprofile.
     * The data that are allowed depend on the `providerName` that is passed. jsonencode
     * can be used for readability as shown in the example above.
     * Changing this updates the existing flavorprofile.
     */
    flavorData: pulumi.Input<string>;
    /**
     * Name of the flavorprofile. Changing this updates the existing
     * flavorprofile.
     */
    name?: pulumi.Input<string>;
    /**
     * The providerName that the flavorProfile will use.
     * Changing this updates the existing flavorprofile.
     */
    providerName: pulumi.Input<string>;
    /**
     * The region in which to obtain the V2 Networking client.
     * A Networking client is needed to create an LB member. If omitted, the
     * `region` argument of the provider is used. Changing this creates a new
     * LB flavorprofile.
     */
    region?: pulumi.Input<string>;
}
