// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.OpenStack.Compute.Outputs
{

    [OutputType]
    public sealed class ServerGroupRules
    {
        public readonly int? MaxServerPerHost;

        [OutputConstructor]
        private ServerGroupRules(int? maxServerPerHost)
        {
            MaxServerPerHost = maxServerPerHost;
        }
    }
}
