// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./configuration";
export * from "./database";
export * from "./instance";
export * from "./user";

// Import resources to register:
import { Configuration } from "./configuration";
import { Database } from "./database";
import { Instance } from "./instance";
import { User } from "./user";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "openstack:database/configuration:Configuration":
                return new Configuration(name, <any>undefined, { urn })
            case "openstack:database/database:Database":
                return new Database(name, <any>undefined, { urn })
            case "openstack:database/instance:Instance":
                return new Instance(name, <any>undefined, { urn })
            case "openstack:database/user:User":
                return new User(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("openstack", "database/configuration", _module)
pulumi.runtime.registerResourceModule("openstack", "database/database", _module)
pulumi.runtime.registerResourceModule("openstack", "database/instance", _module)
pulumi.runtime.registerResourceModule("openstack", "database/user", _module)
