// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.openstack.identity.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetProjectPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetProjectPlainArgs Empty = new GetProjectPlainArgs();

    /**
     * The domain this project belongs to.
     * 
     */
    @Import(name="domainId")
    private @Nullable String domainId;

    /**
     * @return The domain this project belongs to.
     * 
     */
    public Optional<String> domainId() {
        return Optional.ofNullable(this.domainId);
    }

    /**
     * Whether the project is enabled or disabled. Valid
     * values are `true` and `false`.
     * 
     */
    @Import(name="enabled")
    private @Nullable Boolean enabled;

    /**
     * @return Whether the project is enabled or disabled. Valid
     * values are `true` and `false`.
     * 
     */
    public Optional<Boolean> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * Whether this project is a domain. Valid values
     * are `true` and `false`.
     * 
     */
    @Import(name="isDomain")
    private @Nullable Boolean isDomain;

    /**
     * @return Whether this project is a domain. Valid values
     * are `true` and `false`.
     * 
     */
    public Optional<Boolean> isDomain() {
        return Optional.ofNullable(this.isDomain);
    }

    /**
     * The name of the project.
     * 
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return The name of the project.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The parent of this project.
     * 
     */
    @Import(name="parentId")
    private @Nullable String parentId;

    /**
     * @return The parent of this project.
     * 
     */
    public Optional<String> parentId() {
        return Optional.ofNullable(this.parentId);
    }

    /**
     * The id of the project. Conflicts with any of the
     * above arguments.
     * 
     */
    @Import(name="projectId")
    private @Nullable String projectId;

    /**
     * @return The id of the project. Conflicts with any of the
     * above arguments.
     * 
     */
    public Optional<String> projectId() {
        return Optional.ofNullable(this.projectId);
    }

    /**
     * The region the project is located in.
     * 
     */
    @Import(name="region")
    private @Nullable String region;

    /**
     * @return The region the project is located in.
     * 
     */
    public Optional<String> region() {
        return Optional.ofNullable(this.region);
    }

    private GetProjectPlainArgs() {}

    private GetProjectPlainArgs(GetProjectPlainArgs $) {
        this.domainId = $.domainId;
        this.enabled = $.enabled;
        this.isDomain = $.isDomain;
        this.name = $.name;
        this.parentId = $.parentId;
        this.projectId = $.projectId;
        this.region = $.region;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetProjectPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetProjectPlainArgs $;

        public Builder() {
            $ = new GetProjectPlainArgs();
        }

        public Builder(GetProjectPlainArgs defaults) {
            $ = new GetProjectPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param domainId The domain this project belongs to.
         * 
         * @return builder
         * 
         */
        public Builder domainId(@Nullable String domainId) {
            $.domainId = domainId;
            return this;
        }

        /**
         * @param enabled Whether the project is enabled or disabled. Valid
         * values are `true` and `false`.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Boolean enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param isDomain Whether this project is a domain. Valid values
         * are `true` and `false`.
         * 
         * @return builder
         * 
         */
        public Builder isDomain(@Nullable Boolean isDomain) {
            $.isDomain = isDomain;
            return this;
        }

        /**
         * @param name The name of the project.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        /**
         * @param parentId The parent of this project.
         * 
         * @return builder
         * 
         */
        public Builder parentId(@Nullable String parentId) {
            $.parentId = parentId;
            return this;
        }

        /**
         * @param projectId The id of the project. Conflicts with any of the
         * above arguments.
         * 
         * @return builder
         * 
         */
        public Builder projectId(@Nullable String projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param region The region the project is located in.
         * 
         * @return builder
         * 
         */
        public Builder region(@Nullable String region) {
            $.region = region;
            return this;
        }

        public GetProjectPlainArgs build() {
            return $;
        }
    }

}
